#!/bin/bash
#
# Copyright (c) 2023-2024. Permar AI Inc.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#
#

# Exit with error
set -eo pipefail

# Environment
GIT_HOOKS=".githooks"

# Script execution
if [ -x "$(command -v "node")" ]; then
  node "${GIT_HOOKS}/pre-commit.js"
  git add version.json
fi
npm run format:add

exit 0
